# Spring properties
spring:
  output:
    ansi:
      enabled: always
  application:
    name: prototype  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    mode: HTML5
  profiles:
    active:
      - @spring.active.profile@    # Default profile specified @ pom maven file

  #database configuration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/mvcprototype_enc
    username: postgres
    password: ENC(qXHHVp8oEz/rKZGtnDBM8Yudjq7ZsF5u) #postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: HikariPool
      idle-timeout: 10000
      data-source-properties:
        - hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
        - hibernate.show_sql: true
        - database.stmt.cache.stmt: true
        - database.stmt.cache.size: 250
        - database.stmt.cache.sql.limit: 2048
        - database.stmt.use.server: true
        - hibernate.jdbc.lob.non_contextual_creation: false

  jpa:
    generate-ddl: true
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true

  #message source
  messages:
    basename: message/pages, message/controls, message/messages, message/httperrors

 
#logging
logging:
  
  level:
    root: INFO
    org.jasypt: INFO
    org.hibernate: INFO
    com.prototype: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO



debug: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: p@ssw0rd


application:

  #bdd encryptor : PBEWithMD5AndTripleDES, >>PBEWITHSHA256AND128BITAES-CBC-BC (bouncy castle)
  bdd-encryptor:
    algorithm: ENC(2uBb/AmWVUhAbT6H+6wLicroCtfidyeMOg6pO/yVNjJFXg/RPxJAeFFg3pgLm2at) #PBEWITHSHA256AND128BITAES-CBC-BC
    password: ENC(BzPg4MpcyHKyfjcCXsXxn4brrm7zHAR1) #3t3ch_p@ssW0rd
    pool-size: 20
 
  #security
  security:
    rolesHierarchy: ROLE_ADMIN > ROLE_USER
    admin:
      pattern: /admin/**    #ant pattern pour role ADMIN

  #data generation    
  production:
    mode: false
  database:
    generate:
      data: true
    file:
      user: classpath:data/default_user.txt
  default:
    locale: fr
    encoding: utf8

  #localisation
  i18n:
    dir:
      page: classpath:message/pages
      control: classpath:message/controls
      message: classpath:message/messages
      http-error: classpath:message/httperrors

  #token
  oauth2:
    jwt:
      jks-file: __security__/prototypekeys.jks
      password: 123456
      alias: prototypekeys
      public-key: __security__/prototype.pbk
    token:
      validity:
        second:
          access: 180 #86400
          refresh: 1800 #172800
    client:
      client-id: prototype-client
      secret-key: $2a$10$MtgDhalQE/BS./FMZkWVCe3huet/iogZeJe0RhhRE3N7NaPukqcA2 #prototype-client

  #version
  version: @pom.version@

server:
  session:
    cookie:
      name: _prototype_cookie_    



---
spring:
  profiles: local

server:
  port: 8080
  servlet:
    context-path: /
